name: 'Install pnpm and dependencies'
description: 'Install Node.js pnpm and dependencies'
inputs:
  node-version: 
    description: 'Node version number or version name'
    required: false
    default: 18.16.0
runs:
  using: 'composite'
  steps:
    - name: 'use Node.js ${{ inputs.node-version }}'
      uses: actions/setup-node@v3
      with: 
        node-version: ${{ inputs.node-version }}
    - name: 'install pnpm'
      run: npm -g install pnpm
      shell: bash
    - name: 'install dependencies'
      run: pnpm install --frozen-lockfile
      shell: bash