name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: ./.github/actions/setup
      - name: run lint
        run: pnpm run lint
  
 