name: Release

on:
  push:
    branches:
      - main

jobs:  
  release:
    if: ${{ contains(github.event.head_commit.message, '[patch]') || contains(github.event.head_commit.message, '[minor]') || contains(github.event.head_commit.message, '[major]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: ./.github/actions/setup
      - name: Build
        run: pnpm run build  
      - run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      - run: git config user.email "xiaoweihsueh@gmail.com"
      - run: git config user.name "Hsuehic"
      - name: Version
        run: npm version patch
        if: ${{ contains(github.event.head_commit.message, '[patch]') }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.PAT }}
      - run: npm version minor
        if: ${{ contains(github.event.head_commit.message, '[minor]') }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - run: npm version major
        if: ${{ contains(github.event.head_commit.message, '[minor]') }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: git push
        env:
          GH_TOKEN: ${{ secrets.PAT }}